### ISSUE TITLE
Typo / placeholder text in "Milestones" section

### ISSUE THREAD

**Issue by andrewferguson** [louis-threedots/ProjectPlan#3]
> We have defined the following milestones and evaluation **methods(measures?)** based on the technical goals

**Comment by andrewferguson** [comment]
Ah, my fault. I didn't realise you need to alter the compilation order:

`pdflatex` then `bibtex` then `pdflatex` then `pdflatex` again.

**Comment by Canbenix** [comment]
https://github.com/louis-threedots/ProjectPlan/pull/11
